version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/andreirechkov/go-skeleton
